### ISSUE TITLE
static_vector alignment breaks visual studio (2017) debugging

### ISSUE THREAD

**Issue by DunkUK** [Chobolabs/chobo-shl#13]
Not sure if this can be worked around by changing the code directly, but after some hours of revising NatVis I managed to find a definition that seems to work:

```
<Type Name="chobo::static_vector&lt;*&gt;">
    <DisplayString>{{size = {m_size}}}</DisplayString>
    <Expand>
      <Item Name="Type">"$T1"</Item>
      <ArrayItems>
        <Size>m_size</Size>
        <ValuePointer>($T1*)(this)</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
```
It might be useful for future Visual Studio users to include a natvis file for the different classes.
Anyway, thank you for the library!

**Comment by iboB** [comment]
Cool. Why don't you make a pull request adding a `chobo_static_vector.natvis` file in `tools/vs`?
