### ISSUE TITLE
about some_type::operator=(some_type const &other)

### ISSUE THREAD

**Issue by mm304321141** [Chobolabs/chobo-shl#2]
need this ?

```
some_type &some_type::operator=(some_type const &other)
{
    if(this != &other)
    {
        // do something 
    }
    return *this;
}
```

**Comment by iboB** [comment]
I'm not sure I understand. All classes have an assignment operator.

**Comment by pdobrev** [comment]
The check whether you're assigning it to the same thing (hence noop) is missing, it seems.

**Comment by iboB** [comment]
Ah, self usurp checks. Those are indeed needed for `static_vector`, `flat_map`
