### ISSUE TITLE
Swap is not implemented in `static_vector`

### ISSUE THREAD

**Issue by jcelerier** [Chobolabs/chobo-shl#5]
It would make it more of a drop-in replacement

**Comment by iboB** [comment]
Done. Keep in mind though, that `static_vector::swap` is not (and cannot) be as fast and simple as `std::vector::swap`. It actually swaps elements piece-wise

**Comment by jcelerier** [comment]
cool, thank you very much for you reactivity ! my problem was when using `boost::algorithms::split` which ends up calling swap at some point
