### ISSUE TITLE
small_vector: conflict between constructors.

### ISSUE THREAD

**Issue by jcelerier** [Chobolabs/chobo-shl#6]
The following : 

    chobo::small_vector<std::size_t> vec(5, 0); 

does not compile; it triggers the `small_vector(InputIterator first, InputIterator last)` constructor (and then fails when trying to dereference in `assign_impl`) .

I could solve it quickly by a small sfinae if this can be useful:

    template <class InputIterator, typename = decltype(*(std::declval<InputIterator>()))>

**Comment by iboB** [comment]
Thanks. We actually had multiple ways to trigger the same compilation error. I fixed them all in the last commit.
