### ISSUE TITLE
Will there be a flat_hash in future?

### ISSUE THREAD

**Issue by ddengster** [Chobolabs/chobo-shl#7]
Hi, I've been using flat_map as a replacement for std::map, and I've been liking the ease of integration (literally just renaming my structures and it works!). My question is, will there be a flat_hash in the future that replaces unordered_map?

**Comment by iboB** [comment]
`unordered_map` is already "flat". The benefit of `flat_map` is that it maintains a sorted structure while keeping the data cache-local in a contiguous memory block. `unordered_map` internally keeps the data in a contiguous (and unsorted) memory block (albeit sparse).

**Comment by ddengster** [comment]
Hm I always thought that unordered_map was a linked list implementation, with nodes allocated dynamically. In any case, thanks! I'll close the issue.

**Comment by iboB** [comment]
Hash clashes are typically stored in linked lists but they are expected to be rare. I guess some cache-friendly optimizations could be designed around that. 

In any case though, it's highly unlikely that we'll work on something like that in the near future
